[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
